"""initial schema

Revision ID: edce10f23379
Revises:
Create Date: 2026-05-28 11:08:15.884182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edce10f23379"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_response_status", sa.Integer(), nullable=True),
        sa.Column("source_content_hash", sa.Text(), nullable=True),
        sa.Column("rows_seen", sa.Integer(), nullable=True),
        sa.Column("rows_created", sa.Integer(), nullable=True),
        sa.Column("rows_updated", sa.Integer(), nullable=True),
        sa.Column("rows_removed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_html_snapshot_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trusted_flagger_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tf_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scrape_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("idx_tfe_tf", "trusted_flagger_events", ["tf_id", "occurred_at"], unique=False)
    op.create_index("idx_tfe_time", "trusted_flagger_events", ["occurred_at"], unique=False)
    op.create_table(
        "trusted_flaggers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("legal_form", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("email_domain", sa.Text(), nullable=True),
        sa.Column("address_raw", sa.Text(), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("dsc_name", sa.Text(), nullable=True),
        sa.Column("dsc_country_code", sa.CHAR(length=2), nullable=True),
        sa.Column(
            "areas_of_expertise_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("areas_of_expertise", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("designation_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_hash", sa.Text(), nullable=False),
        sa.Column("source_snapshot_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tf_areas_gin",
        "trusted_flaggers",
        ["areas_of_expertise"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_tf_country", "trusted_flaggers", ["country_code"], unique=False)
    op.create_index("idx_tf_email_domain", "trusted_flaggers", ["email_domain"], unique=False)
    op.create_index("idx_tf_status", "trusted_flaggers", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tf_status", table_name="trusted_flaggers")
    op.drop_index("idx_tf_email_domain", table_name="trusted_flaggers")
    op.drop_index("idx_tf_country", table_name="trusted_flaggers")
    op.drop_index("idx_tf_areas_gin", table_name="trusted_flaggers", postgresql_using="gin")
    op.drop_table("trusted_flaggers")
    op.drop_index("idx_tfe_time", table_name="trusted_flagger_events")
    op.drop_index("idx_tfe_tf", table_name="trusted_flagger_events")
    op.drop_table("trusted_flagger_events")
    op.drop_table("scrape_runs")
    # ### end Alembic commands ###
